apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: waiter
  name: waiterpod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 20; touch /tmp/ready.txt; while true; do sleep 10; echo "infinitely ready now..."; done 
    image: busybox
    name: waitercontainer
    resources: {}
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready.txt
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Never